### PR TITLE
Fix for issue #2 prevent lc on uninit var

### PR DESCRIPTION
**Pull request by lancew**
Prevent the calling of lc on uninitialised value.

Hi, as part of the PRC I took a look and spotted this outstanding issue. Written a quick fix and test.
All tests pass, but you might have opinion on if what I have done suits what you would like to see in the code.
Lance

### CODE REVIEW

**Comment by kablamo** [comment]
Nice!  Its awsome that you wrote a test for it thank you.  I thought it was kinda cool how I had 100% test coverage but still had a bug.

**Comment by kablamo** [comment]
hmmm

```
kebab_case("____"); # returns empty string
```

I'm not sure what it should return.  I think it should return "____".  Or "----"....

**Comment by kablamo** [comment]
I don't know... it doesn't make a lot of sense to ask someone to camel case or kebab case a string like "____" or "-_ ".  Maybe it should just die.  I'm already returning "" when a user passes in "" though.  Probably should have died when they passed in "".

**Comment by kablamo** [comment]
Ok I think I like this solution.  I did a release for this.  Should show up on cpan soon.

**Comment by lancew** [comment]
Yeah, I tended to think along same lines as you that dieing might be fine; but like you spotted the existing "" returns "" and thought my change pretty much replicates that approach. 
Glad to contribute

**Pull request merged**
